#pragma once
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <memory>
#include <optional>
#include <queue>
#include <rtaudio/RtAudio.h>
#include <rtmidi/RtMidi.h>
#include <thread>
#include <vector>